/* 
				Criando as tabelas
*/
--
CREATE TABLE REPOUSO_REMUNERADO(
	BONUS_PORC DECIMAL(5,2) DEFAULT 0
)

--
INSERT INTO REPOUSO_REMUNERADO VALUES (1)

--
SELECT * FROM REPOUSO_REMUNERADO

-- CRIAÇÃO DA TABELA DE GRATIFICAÇÃO POR ESCOLARIDADE
CREATE TABLE GRATIFICACAO_POR_ESCOLARIDADE(
	ID CHAR(1),
	ESCOLARIDADE VARCHAR(20) NOT NULL,
	BONUS_PORC DECIMAL(5,2) NOT NULL,
	PRIMARY KEY(ID)
)

-- INSERINDO VALORES
INSERT INTO GRATIFICACAO_POR_ESCOLARIDADE
VALUES
('S', 'MEDIO', 0),
('G', 'GRADUADO', 18),
('E', 'ESPECIALIZACAO', 25),
('M', 'MESTRADO', 54),
('D', 'DOUTORADO', 104)

-- SELECT
SELECT * FROM GRATIFICACAO_POR_ESCOLARIDADE ORDER BY BONUS_PORC

CREATE TABLE AUXILIO_ALIMENTACAO(
	AUXILIO MONEY DEFAULT 0
)

--
INSERT INTO AUXILIO_ALIMENTACAO VALUES (750)

--
SELECT * FROM AUXILIO_ALIMENTACAO

--Salário familia
CREATE TABLE SALARIO_FAMILIA(
	FAIXA INT,
	SMIN MONEY NOT NULL,
	SMAX MONEY NOT NULL,
	S_FAMILIA MONEY NOT NULL,
	PRIMARY KEY(FAIXA)
)
--
INSERT INTO SALARIO_FAMILIA VALUES
(1, 0, 1655.98, 56.47)

--
SELECT * FROM SALARIO_FAMILIA
--

CREATE TABLE BONUS_POR_ANO_TRABALHADO(
	BONUS MONEY NOT NULL
)

--
INSERT INTO BONUS_POR_ANO_TRABALHADO VALUES (125)

--
SELECT * FROM BONUS_POR_ANO_TRABALHADO

CREATE TABLE VALE_CULTURA(
	BONUS MONEY NOT NULL
)

--
INSERT INTO VALE_CULTURA VALUES (80)

--
SELECT * FROM VALE_CULTURA
--
--
CREATE TABLE VALE_TRANSPORTE(
	PORC DECIMAL(5,2)
)

-- VALOR
INSERT INTO VALE_TRANSPORTE VALUES (6)

-- 
SELECT * FROM VALE_TRANSPORTE
--

CREATE TABLE PLANO_SAUDE_EMPRESARIAL
(
	TAXA_FUNCIONARIO NUMERIC(5,2) NOT NULL,
	TAXA_DEPENDENTE NUMERIC(5,2) NOT NULL
)
--
INSERT INTO PLANO_SAUDE_EMPRESARIAL (TAXA_FUNCIONARIO, TAXA_DEPENDENTE) VALUES (3.75, 1.15)
--
SELECT * FROM PLANO_SAUDE_EMPRESARIAL
--

-- INSS
CREATE TABLE CONTRIBUICAO_PREVIDENCIARIA_INSS(
	FAIXA INT PRIMARY KEY,
	VMIN MONEY NOT NULL,
	VMAX MONEY NOT NULL,
	ALIQUOTA NUMERIC(5,2) NOT NULL
)
--INSS_Teto
CREATE TABLE CONTRIBUICAO_INSS_TETO(
	FAIXA INT PRIMARY KEY,
	VMIN MONEY NOT NULL,
	VMAX MONEY NOT NULL,
	VALOR MONEY NOT NULL
)

-- INSERINDO VALORES
INSERT INTO CONTRIBUICAO_PREVIDENCIARIA_INSS
(FAIXA, VMIN, VMAX, ALIQUOTA)
VALUES	(1, 0, 1212, 7.5),
		(2, 1212.01, 2427.35, 9),
		(3, 2427.36, 3641.03, 12),
		(4, 3641.04, 7087.22, 14) 

INSERT INTO CONTRIBUICAO_INSS_TETO
(FAIXA, VMIN, VMAX, VALOR)
VALUES (5, 7087.23, 99999.99, 992.21)
--
SELECT * FROM CONTRIBUICAO_INSS_TETO

-- CRIANDO A TABELA CONTENDO O VALOR A DEDUZIR DO DEPENDENTE
CREATE TABLE DEPENDENTE (
	DEDUCAO MONEY NOT NULL
)

-- INSERINDO O VALOR
INSERT INTO DEPENDENTE VALUES (189.59)

-- TESTE
SELECT * FROM DEPENDENTE

-- CRIANDO TABELA DO IMPOSTO DE RENDA
CREATE TABLE IRRF(
	VMIN DECIMAL(10,2) NOT NULL,
	VMAX DECIMAL(10,2) NOT NULL,
	ALIQ DECIMAL(10,2) NOT NULL,
	PARC DECIMAL(10,2) NOT NULL
)

-- INSERINDO OS VALORES DO IMPOSTOS DE RENDA
INSERT INTO IRRF VALUES
(0 , 1903.98 , 0 , 0 ),
(1903.99, 2826.65 , 7.5 , 142.8 ),
(2826.66, 3751.06 , 15 , 354.8 ),
(3751.07, 4664.68 , 22.5 , 636.13),
(4664.69, 99999.99 , 27.5 , 869.36)

-- TESTE
SELECT * FROM IRRF

-- PORCENTAGEM DO FGTS
CREATE TABLE FGTS(
	PERCENTUAL DECIMAL (5,2) NOT NULL
)

-- INSERINDO O PERCENTUAL
INSERT INTO FGTS VALUES (8)

-- TESTE
SELECT * FROM FGTS