------------------------------------------------------------------------

CREATE PROCEDURE SP_CALCULAR_INSS
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DESCONTO_INSS MONEY OUTPUT)
AS
BEGIN
    IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
        BEGIN
            DECLARE    
					@ALIQUOTA DECIMAL(5,3),
                    @DIFERENCA MONEY,
                    @AGREGADO MONEY,
                    @FAIXA INT,
                    @SALARIO_BRUTO MONEY,
                    @SALARIO_CONTRIBUICAO MONEY

            -- DEFININDO O VALOR DO SALARIO BRUTO
            EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

            -- DEFININDO O SALARIO DE CONTRIBUIÇÃO
            SET @SALARIO_CONTRIBUICAO = @SALARIO_BRUTO
			

            -- VERIFICANDO SE O SALARIO É MAIOR QUE O TETO DO INSS, SE FOR RETORNAR O DESCONTO_INSS E ENCERRA A PROCEDURE
            IF @SALARIO_CONTRIBUICAO > (SELECT VMAX FROM CONTRIBUICAO_PREVIDENCIARIA_INSS WHERE FAIXA = 4)
            BEGIN
                    SELECT @DESCONTO_INSS = VALOR FROM CONTRIBUICAO_INSS_TETO WHERE FAIXA = 5
			END
            -- SE NÃO FOR MAIOR, EXECUTA ISSO
            ELSE 
                BEGIN
                    -- DEFININDO A FAIXA, ALIQUOTA REFERENTE AO SALARIO DE CONTRIBUICAO
                    SELECT    @FAIXA = FAIXA,
                            @ALIQUOTA = ALIQUOTA/100
                    FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
                    WHERE @SALARIO_BRUTO BETWEEN VMIN AND VMAX
                
                    --DEFININDO A DIFERENÇA A SER TIRADA
                    SET @DESCONTO_INSS = (@SALARIO_CONTRIBUICAO * @ALIQUOTA)
				END
    END
END


--CHAMADA DA PROCEDURE
DECLARE	@INSS DECIMAL(5,2)
EXEC SP_CALCULAR_INSS 1068, @INSS OUTPUT 
SELECT @INSS AS DESCONTO_DO_INSS

SELECT * FROM CARGOS
SELECT * FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
------------------------------------------------------------------------

CREATE PROCEDURE SP_VALE_TRANSPORTE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @VALE_TRANSPORTE MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- SE TIVER DESCONTO E DIREITO, SERÁ CALCULADO
			IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS WHERE VALE_TRANSP = 'S')
				BEGIN
					-- VARIAVEL LOCAL
					DECLARE @SALARIO_BRUTO MONEY

					-- SETANDO VALOR DO SALARIO BRUTO
					EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

					SELECT @VALE_TRANSPORTE = @SALARIO_BRUTO * PORC / 100 FROM VALE_TRANSPORTE
				END
			ELSE -- SE NÃO TIVER O DESCONTO
				BEGIN
					SET @VALE_TRANSPORTE = 0
				END
		END
	ELSE
		BEGIN
			SET @VALE_TRANSPORTE = -1
			PRINT 'SP_VALE_TRANSPORTE: MATRÍCULA INVÁLIDA'
		END
END

-- TESTE
/* MATRICULAS COM 'S' NO VALE_TRANSP
1002
1010
1045
1054
1065
1067

IMMPRESSÃO DESSAS PESSOAS

*/

DECLARE @VALE MONEY
EXEC SP_VALE_TRANSPORTE 1065, @VALE OUTPUT
SELECT @VALE AS VALE_TRANSPORTE

------------------------------------------------------------------------

-- PROCEDURE PARA CALCULAR O DESCONTO DO PLANO DE SAUDE
CREATE PROCEDURE SP_PLANO_SAUDE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DESCONTO_PLANO_SAUDE MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL DA PROCEDURE
			DECLARE @TAXA_FUNCIONARIO DECIMAL(5,2),
					@TAXA_DEPENDENTE DECIMAL(5,2),
					@DEPENDENTE INT,
					@PLANO_SAUDE CHAR(5),
					@SALARIO_BRUTO MONEY

			-- DEFININDO SALARIO BRUTO
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

			-- DEFININDO AS TAXAS
			SELECT @TAXA_FUNCIONARIO = TAXA_FUNCIONARIO, @TAXA_DEPENDENTE =	TAXA_DEPENDENTE FROM PLANO_SAUDE_EMPRESARIAL

			-- EXTRAINDO INFORMAÇÕES PARA REALIZAR OS CALCULOS
			SELECT @PLANO_SAUDE = PLANO_SAUDE, @DEPENDENTE = DEPENDENTES FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA_FUNCIONARIO

			IF @PLANO_SAUDE = 'S' 
				IF @DEPENDENTE = 0
				SET @DESCONTO_PLANO_SAUDE = @SALARIO_BRUTO * (@TAXA_FUNCIONARIO/100)
				IF @DEPENDENTE > 0
				SET @DESCONTO_PLANO_SAUDE = @SALARIO_BRUTO * ((@TAXA_FUNCIONARIO + (@TAXA_DEPENDENTE*@DEPENDENTE))/100)

			IF @PLANO_SAUDE = 'N'
				SET @DESCONTO_PLANO_SAUDE = 0
		END
	ELSE 
		BEGIN
			SET @DESCONTO_PLANO_SAUDE = -1
			PRINT 'SP_PLANO_SAUDE: MATRÍCULA INVÁLIDA!'
		END
END

-- TESTE
DECLARE @DESCO_SAUDE MONEY 
EXEC SP_PLANO_SAUDE  1060,@DESCO_SAUDE OUTPUT
SELECT @DESCO_SAUDE AS DESCONTO_PLANO_SAUDE

SELECT * FROM CARGOS


------------------------------------------------------------------------

CREATE PROCEDURE SP_DEDUCAO_POR_DEPENDENTE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DEDUCAO_TOTAL MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL LOCAL
			DECLARE @QTD_DEPENDENTES INT,
					@DEDUCAO MONEY

			-- OBTENDO A QUANTIDADE DE DEPENDENTES
			SELECT @QTD_DEPENDENTES = DEPENDENTES
			FROM FUNCIONARIOS
			WHERE MATRICULA = @MATRICULA_FUNCIONARIO

			-- OBTENDO O VALOR DE DEDUÇÃO
			SELECT @DEDUCAO = DEDUCAO FROM DEPENDENTE

			--RETORNANDO O VALOR DE DEDUÇÃO POR DEPENDETES
			SET @DEDUCAO_TOTAL = @QTD_DEPENDENTES * @DEDUCAO
		END
	ELSE
		BEGIN
			SET @DEDUCAO = -1
			PRINT 'SP_DEDUCAO_POR_DEPENDENTE: MATRÍCULA INVÁLIDA'
		END
END

-- SELECT MATRICULA, DEPENDENTES FROM FUNCIONARIOS

-- TESTE
DECLARE @VALOR MONEY
EXEC SP_DEDUCAO_POR_DEPENDENTE 1002, @VALOR OUTPUT
SELECT @VALOR AS "VALOR A SER DEDUZIDO"


------------------------------------------------------------------------

CREATE PROCEDURE SP_CALCULAR_IRRF
(@MATRICULA_FUNCIONARIO VARCHAR(4), @VALOR_IRRF DECIMAL(7,2) OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEIS
			DECLARE @ALIQUOTA MONEY,
					@PARC MONEY,
					@SALARIO_BRUTO MONEY,
					@INSS MONEY,
					@DEPENDENTES MONEY,
					@BASE_CALCULO MONEY

			-- SETANDO OS VALORES DAS VARIAVEIS
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT
			
			-- SETANDO O VALOR DO INSS
			EXEC SP_CALCULAR_INSS @MATRICULA_FUNCIONARIO, @INSS OUTPUT

			-- SETANDOS A DEDUCAO POR DEPENDENTES
			EXEC SP_DEDUCAO_POR_DEPENDENTE @MATRICULA_FUNCIONARIO, @DEPENDENTES OUTPUT

			-- SETANDO A BASE DE CALCULO -> (SALARIO BRUTO - INSS)
			SET @BASE_CALCULO = @SALARIO_BRUTO - @INSS - @DEPENDENTES

			-- SETANDO OS VALORES DA ALIQUOTA E PARC
			SELECT	@ALIQUOTA = ALIQ,
					@PARC = PARC
			FROM IRRF
			WHERE @BASE_CALCULO > VMIN AND @BASE_CALCULO <=VMAX

			-- SETANDO O VALOR DO IMPOSTO DE RENDA
			SET @VALOR_IRRF = (@BASE_CALCULO * (@ALIQUOTA / 100)) - @PARC

			-- SETANDO O VALOR DO IMPOSTO DE RENDA EM ZERO, CASO POR ALGUM MOTIVO FIQUE NEGATIVO
			IF @VALOR_IRRF < 0
				SET @VALOR_IRRF = 0
		END
	ELSE
		BEGIN
			SET @VALOR_IRRF = -1
			PRINT 'SP_CALCULAR_IRRF: MATRÍCULA INVÁLIDA!'
		END
END

-- TESTE
DECLARE @IRRF MONEY
EXEC SP_CALCULAR_IRRF 1068, @IRRF OUTPUT
SELECT @IRRF AS IRRF

SELECT * FROM CARGOS