---------------------------------SALARIO BRUTO---------------------------------------
CREATE PROCEDURE SP_SALARIO_BRUTO
(@MATRICULA_FUNCIONARIO VARCHAR(4), @SAL_BRUTO MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			SELECT	@SAL_BRUTO = C.SALARIO
			FROM	FUNCIONARIOS F
				INNER JOIN CARGOS C ON C.CARGO = F.CARGO
			WHERE F.MATRICULA = @MATRICULA_FUNCIONARIO
		END
	ELSE
		BEGIN
			SET @SAL_BRUTO = -1
			PRINT 'SP_SALARIO_BRUTO: MATRÍCULA INVÁLIDA'
		END
END

---------------------------------REPOUSO REMUNERADO---------------------------------------
-- CRIACAO DA PROCEDURE DO CALCULO DO REPOUSO REMUNERADO

CREATE PROCEDURE SP_REPOUSO_REMUNERADO
(@MATRICULA_FUNCIONARIO VARCHAR(4), @BONUS_REPOUSO MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEIS DA PROCEDURE
			DECLARE @PORC DECIMAL(5,2),
					@SALARIO_BRUTO MONEY
	
			--DEFININDO O SALARIO BRUTO
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

			-- DEFININDO O PERCENTUAL DE BONUS
			SET @PORC = (SELECT * FROM REPOUSO_REMUNERADO) / 100
	
			-- DEFININDO O VALOR DO SALARIO REPOUSO
			SET @BONUS_REPOUSO = @SALARIO_BRUTO * @PORC
		END
	ELSE
		BEGIN
			SET @BONUS_REPOUSO = -1
			PRINT 'SP_REPOUSO_REMUNERADO: MATRICULA INVALIDO!'
		END
END

-- TESTE
DECLARE @REPOUSO_REMU MONEY

EXEC SP_REPOUSO_REMUNERADO 1060, @REPOUSO_REMU OUTPUT
SELECT	@REPOUSO_REMU AS REMUNERACAO

-------------------------------GRATIFICAÇÃO POR ESCOLARIDADE-----------------------------------------

-- PROCEDURE PARA CALCULAR A GRATIFICACAO POR ESCOLARIDADE (GPE)
CREATE PROCEDURE SP_GRATIFICACAO_POR_ESCOLARIDADE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @BONUS_GPE MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEIS DA PROCEDURE
			DECLARE @PORC DECIMAL(5,2),
					@SALARIO_BRUTO MONEY,
					@GRAU_ESCOL VARCHAR(1)

			-- SETANDO VALORES
			SELECT	@SALARIO_BRUTO = C.SALARIO,		-- DEFININDO O SALARIO BRUTO
					@GRAU_ESCOL = F.ESCOLARIDADE	-- DEFININDO O GRAU DE ESCOLARIDADE
			FROM	FUNCIONARIOS F
					INNER JOIN CARGOS C ON C.CARGO = F.CARGO
			WHERE F.MATRICULA = @MATRICULA_FUNCIONARIO
	
			-- DEFININDO O PERCENTUAL A SER PAGO
			SET @PORC = (SELECT BONUS_PORC FROM GRATIFICACAO_POR_ESCOLARIDADE WHERE ID LIKE @GRAU_ESCOL) / 100

			SET @BONUS_GPE = @SALARIO_BRUTO * @PORC
		END
	ELSE
		BEGIN
			SET @BONUS_GPE = -1
			PRINT 'SP_GRATIFICACAO_POR_ESCOLARIDADE: MATRICULA INVÁLIDA!' 
		END
END

--TESTE
DECLARE @GPE MONEY
EXEC SP_GRATIFICACAO_POR_ESCOLARIDADE 1060, @GPE OUTPUT
SELECT @GPE AS GPE


------------------------------------------------------------------------

SELECT * FROM FUNCIONARIOS
SELECT * FROM CARGOS

---------------------------------------SALARIO FAMILIA---------------------------------

-- PROCEDURE DE CALCULO DO SALARIO FAMILIA
CREATE PROCEDURE SP_SALARIO_FAMILIA
(@MATRICULA_FUNCIONARIO VARCHAR(4), @TOTAL_S_FAM MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL DA PROCEDURE
			DECLARE @SALARIO_BRUTO MONEY
			DECLARE @SALARIO_FAMILIA MONEY
			DECLARE @DEPENDENTES INT
			SET @DEPENDENTES = (SELECT DEPENDENTES FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA_FUNCIONARIO)

			-- DEFININDO O SALARIO BRUTO 
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT
	
			SET @SALARIO_FAMILIA = (SELECT S_FAMILIA FROM SALARIO_FAMILIA WHERE @SALARIO_BRUTO BETWEEN SMIN AND SMAX)
			
			IF @SALARIO_FAMILIA IS NULL
				SET @SALARIO_FAMILIA = 0

			SET @TOTAL_S_FAM = @SALARIO_FAMILIA * @DEPENDENTES

		END
	ELSE
		BEGIN
			SET @SALARIO_FAMILIA = -1
			PRINT 'SP_SALARIO_FAMILIA: MATRICULA INVALIDO!'
		END
END

-- TESTE
DECLARE @SAL_FAM MONEY
EXEC SP_SALARIO_FAMILIA 1054, @SAL_FAM OUTPUT
SELECT @SAL_FAM AS SALARIO_FAMILY

SELECT * FROM FUNCIONARIOS

-----------------------------------------ANUENIO-------------------------------

CREATE PROCEDURE SP_ANUENIO
(@MATRICULA VARCHAR(4), @BONUS_ANUENIO MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			--VARIVEIS DA PROCEDURE
			DECLARE @DATA_ATUAL DATE,
					@DATA_ADMISSAO DATE,
					@BONUS_PAT DECIMAL(5,2), 
					@ANOS_TRAB INT

			-- PEGANDO A DATA DO SISTEMA E CONVERTENDO PARA O TIPO DATE
			SET @DATA_ATUAL = CONVERT(DATE,GETDATE())

			-- PEGANDO A DATA QUE O FUNCIONARIO FOI CONTRATADO
			SET @DATA_ADMISSAO = (SELECT ADMISSAO FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA)
	
			-- PEGANDO O VALOR DO BONUS POR ANO TRABALHADO
			SET @BONUS_PAT = (SELECT * FROM BONUS_POR_ANO_TRABALHADO)
	
			-- OBTENDO A DIFERENÇA ENTRE A DATA ATUAL E A DATA EM QUE O FUNCIONARIO FOI CONTRATADO
			SET @ANOS_TRAB = CONVERT(INT, DATEDIFF(DAY, @DATA_ADMISSAO, @DATA_ATUAL) / 365.25)
	
			-- DEFININDO O BONUS POR ANO(S) DE TRABALHO(S)
			SET @BONUS_ANUENIO =  @ANOS_TRAB * @BONUS_PAT
		END
	ELSE
		BEGIN
			PRINT 'SP_ANUENIO: MATRÍCULA INVÁLIDA'
			SET @BONUS_ANUENIO = -1
		END
END

-- TESTE
DECLARE @BONUSITO MONEY
EXEC SP_ANUENIO 1068, @BONUSITO OUTPUT
SELECT @BONUSITO AS ANUENIO

SELECT * FROM FUNCIONARIOS


-------------------------------SOMA DOS PROVENTOS-----------------------------------------

CREATE PROCEDURE SP_SOMAR_PROVENTOS
(@MATRICULA_FUNCIONARIO VARCHAR(4), @PROVENTOS MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS) -- VALIDANDO A MATRICULA
		BEGIN
			-- VARIAVEIS DA PROCEDURE
			DECLARE @REPOUSO_REMUNERADO MONEY,
					@GRATIFICACAO_ESCOLADRIDADE MONEY,
					@AUX_ALIMENTACAO MONEY,
					@TOTAL_S_FAM MONEY,
					@ANUENIO MONEY,
					@VALE_CULTURA MONEY

			-- DEFININDO O VALOR DO REPOUSO REMUNERADO
			EXEC SP_REPOUSO_REMUNERADO @MATRICULA_FUNCIONARIO, @REPOUSO_REMUNERADO OUTPUT

			-- DEFININDO O VALOR DO BONUS POR ESCOLARIDADE
			EXEC SP_GRATIFICACAO_POR_ESCOLARIDADE @MATRICULA_FUNCIONARIO, @GRATIFICACAO_ESCOLADRIDADE OUTPUT

			-- DEFININDO O VALOR DO AUX. ALIMENTAÇÃO
			SELECT @AUX_ALIMENTACAO = AUXILIO FROM AUXILIO_ALIMENTACAO

			-- DEFININDO O SALARIO FAMILIA
			EXEC SP_SALARIO_FAMILIA @MATRICULA_FUNCIONARIO, @TOTAL_S_FAM OUTPUT

			-- DEFININDO O BONUS POR ANO(S) DE TRABALHO(S)
			EXEC SP_ANUENIO @MATRICULA_FUNCIONARIO, @ANUENIO OUTPUT

			-- DEFININDO VALE CULTURA
			SELECT @VALE_CULTURA = BONUS FROM VALE_CULTURA

			-- SOMANDO TODOS OS PROVENTOS
			SET @PROVENTOS = @REPOUSO_REMUNERADO + @GRATIFICACAO_ESCOLADRIDADE + @AUX_ALIMENTACAO + @TOTAL_S_FAM + @ANUENIO + @VALE_CULTURA

			
			--IMPRIMINDO TODOS OS VALORES
			--SELECT	@REPOUSO_REMUNERADO AS REPOUSO_REMUNERADO,
			--		@GRATIFICACAO_ESCOLADRIDADE AS RESCOLARIDADE,
			--		@AUX_ALIMENTACAO AS AUX_ALIMENTACAO,
			--		@TOTAL_S_FAM AS SALARIO_FAMILIA,
			--		@ANUENIO AS ANUENIO,
			--		@VALE_CULTURA AS VALE_CULTURA
			
		END
	ELSE
		PRINT 'SP_SOMAR_PROVENTOS: MATRÍCULA INVÁLIDA'
END

--TESTE
DECLARE @A MONEY
EXEC SP_SOMAR_PROVENTOS 1020, @A OUTPUT
SELECT @A PROVENTOS

SELECT * FROM FUNCIONARIOS WHERE MATRICULA


------------------------------------------------------------------------